### ISSUE TITLE
Should we add the --upgrade flag to pip installation?

### ISSUE THREAD

**Issue by YPCrumble** [jcalazan/ansible-django-stack#143]
Currently the playbook's pip installation is essentially `pip install requirements.txt`. This means that no packages are upgraded beyond the current version if they are already installed.

For existing users of the playbook, this means that a package in requirements.txt that is unpinned will never be upgraded. It also means that if you have a package in your requirements.txt like:

requests==2.0.0

...and then you decide to fork your package and enter this into the requirements.txt file:

git+git://github.com/myusername/requests@my-updated-branch

^ This will not replace the `requests==2.0.0` as expected.

On the other hand, I don't see a downside to adding the --upgrade flag. For users who pin their requirements, this shouldn't cause any problems. Adding the --upgrade flag _will_ upgrade sub-dependencies but only within the version range specified by their parent dependency.

**Comment by DavidCain** [comment]
I'm of the opinion that we should not add an `--upgrade` flag to the installation steps.

As much as possible, builds should be deterministic - running the same Ansible playbook on two different machines should result in the same running application.

I know that the behavior of `pip install` introduces a really unfortunate side effect where "time of last installation" affects the outcome. For example, if you first ran the playbook years ago on a given machine, running the playbook over and over won't change dependencies. However, running the playbook on a _new_ machine will install all your unpinned dependencies to their latest version, rocketing through all the released versions since you first installed your un-pinned dependencies years ago. This is pretty bad, and something that always invoking `--upgrade` would solve!

However, I think it's preferable to have successive Ansible runs on the same host not change the behavior of the application (potentially increasing the possibility of an error!)

I ultimately think that the best solution is either for application authors to:
- Ensure that `requirements.txt` is *only* pinned versions (one way is to [use a separate file](http://www.jfabre.com/how-not-to-to-pip-requirements/) like `requirements-top-level.txt` to state the range of dependencies you'll accept - kind of like a home-grown `package.json` and `package-lock.json`)
- Use a tool like `pipenv` or `poetry` which ensure deterministic installs through the same strategy (one file for expressing dependencies, one file for locking them)

**Comment by YPCrumble** [comment]
@DavidCain I really like this rationale - what I'm going to do is add a flag `pip_use_upgrade_flag` in #185 that allows the user to use `pip --upgrade` if they want to but defaults to `false`.
