### ISSUE TITLE
Use new sample Django project

### ISSUE THREAD

**Issue by jcalazan** [jcalazan/ansible-django-stack#164]
The youtube-dl project that the Django app uses was taken down from GitHub and will probably get removed from PyPI so we need a new sample Django project to link to.

If anyone has an existing Django project that will work with this setup, just let me know and I"ll update the references.

**Comment by jcalazan** [comment]
Closing for now as it might actually be best to just leave it to the user to plug in their own project as the linked project would probably need to also be synced up with compatible versions of specific Ubuntu releases.

**Comment by YPCrumble** [comment]
Wow this is really annoying.

**Comment by StuartMacKay** [comment]
Why not create a bare bones Django project and use that. Whatever `startproject` creates is fine. That would allow you to:

1. clone this project and immediately deploy a working app - no other effort is required.
2. run the tests with no changes to the code.

For me the latter is the most important one. Rather than use this project as a template I want to have one checked out instance and use the command line argument, `--extra-vars` to override all the variables for each project I want to deploy. Molecule does not support --extra-vars so you have two choices: edit the vars in the checked out code or add a file with all the project variables set to the `env_vars` directory and modify the molecule playbook to load them:
```
  vars_files:
    - ../../env_vars/base.yml
    - ../../egnv_vars/vagrant.yml
    - ../../env_vars/tests.yml
```
Having a simple reference project is also useful as everybody is running the tests from the same reference point.
