### ISSUE TITLE
Remove security role?

### ISSUE THREAD

**Issue by jcalazan** [jcalazan/ansible-django-stack#167]
Since this project is mainly designed as a starter template, we might want to just leave it to the users to decide how much security they want to use.

Depending on the cloud provider they use, some of the features in this role may also be redundant (e.g. AWS and DigitalOcean already have managed firewall services so it's not really necessary to activate ufw).

**Comment by YPCrumble** [comment]
@jcalazan like I mentioned in #166 I'd vote to leave this in, but I could see leaving them out more so than the Memcached and other roles more closely coupled to Django.

For me the benefit is having others using/reviewing the code who are also using Django - because sometimes there are bugs that are specific to the framework.

If the additional roles were causing a lot of extra maintenance I agree that removing them makes sense, but it hasn't been too bad recently.

**Comment by StuartMacKay** [comment]
I vote to leave it in for the following reasons:

1. The playbook is not part of the main workflow so there's no overhead in day to day use.
2. There are plenty of deployment options where the service is not as heavily managed as you find at DigitalOcean or AWS. 
3. Security is always best done in layers. Regardless of where my sites are deployed I like the idea of being able to lock it down tight. Judging by the nginx logs in the first hour or so after bringing a droplet online I am rather glad of that even though there are firewalls from the hosting service.
4. It's visible for people to see so security if not just something that somebody else takes care of. That can't be a bad thing.

So, as YPCrumble says, unless it's a maintenance burden, it's a nice to have.
