### ISSUE TITLE
[FEATURE] support docker

### ISSUE THREAD

**Issue by YPCrumble** [jcalazan/ansible-django-stack#72]
@jcalazan have you considered supporting docker containers in this library, or adding some documentation around using the existing playbook with docker? I'd be happy to make a PR if that's interesting.

One interesting approach is [ansible-container](https://github.com/ansible/ansible-container) as used in [this similar repo](https://github.com/ansible/django-gulp-nginx)

**Comment by jcalazan** [comment]
@YPCrumble For now I'd rather keep the repo just Ansible. Documentation sounds good though :+1:

**Comment by jcalazan** [comment]
Closing for now.

**Comment by dpward** [comment]
@jcalazan Would you be open to allowing Vagrant to optionally use Docker as the local VM "provider" instead of VirtualBox? To do this, the command `vagrant up --provider=docker` would be used, which would create one local Docker container instead of one local VirtualBox VM (or connecting to one Amazon Web Services EC2 VM). The Docker container would be provisioned from the same Ansible playbook just as if it were a VirtualBox VM, an AWS VM, etc. Ansible would not need to know anything about Docker, and Docker would not get used when selecting any other Vagrant provider.

I have been testing capability this for a few weeks with Ubuntu 14.04, but I would need to make some changes for Ubuntu 16.04.

**Comment by jcalazan** [comment]
Ah, yeah that actually sounds like a good idea.  Didn't know Docker is supported as a provider.  If we can default to VirtualBox and override the provider via command line that would be pretty neat 

:+1:
